In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification # no need of standerdisation as done already

In [3]:
X,y = make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=15)

In [4]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -0.377957  1.043895  1.043494 -0.101838 -1.617442  0.402713  0.913601   
1   -0.325259  1.276263 -0.686123 -2.463205 -0.489426 -0.240715 -1.469496   
2    0.739019 -0.600903 -0.177294  1.335714 -0.817332 -0.790047  1.457365   
3    0.474312 -1.103002  1.189936 -0.800186  0.912377 -0.406451 -1.130950   
4    0.927365  1.114796  0.080284  1.261064  0.761179  0.921563  0.440832   
..        ...       ...       ...       ...       ...       ...       ...   
995  1.538272  0.171629  0.075371 -0.957658 -1.066219  1.158096 -0.036964   
996 -0.060266  0.095018 -0.271685  1.830560  0.219445 -0.341269  1.180088   
997  0.675563 -0.538420 -1.299500  0.747835  1.733898 -0.268044 -0.520953   
998  2.629710 -2.452899 -1.359785  1.592065  0.854157  1.618828  0.621701   
999 -1.791491 -0.121908  0.535153 -0.588085 -1.929461 -0.659900  0.754921   

            7         8         9  
0   -0.067192  0.175471 -1.049646  
1    1.006633 -0.833692  0.957744  
2   -0.218981  0.878643 -1.257740  
3    1.985111  1.379029  1.041768  
4    0.184645 -1.567739 -0.142107  
..        ...       ...       ...  
995  0.123689  0.927871 -0.225003  
996 -0.216876 -1.752938 -0.810152  
997  2.043336  0.947388  0.790354  
998  0.378898 -1.971894 -0.252250  
999 -1.941357  0.589002 -1.007482  

[1000 rows x 10 columns]

In [5]:
pd.DataFrame(y)

0
0    0
1    0
2    0
3    1
4    1
..  ..
995  0
996  1
997  1
998  1
999  0

[1000 rows x 1 columns]

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [8]:
X_train

array([[ 0.47859902,  0.76582874, -0.1046252 , ..., -1.70357318,
        -0.444856  , -0.72655034],
       [-0.71679033,  0.27851864,  1.51809173, ...,  1.18471701,
        -1.17706573,  0.25255979],
       [-0.53223078, -1.0659123 , -1.00163823, ...,  1.2198129 ,
        -0.31016902, -1.26182012],
       ...,
       [-0.2694684 ,  0.1644042 , -0.28699705, ..., -1.44088094,
         0.74415331, -1.05247282],
       [ 0.04514581, -1.39452086, -1.71849467, ..., -0.98869812,
         0.15247944,  0.58175247],
       [ 1.49372603, -0.24067686,  2.06627838, ..., -0.26705817,
         2.25388779,  0.61822566]], shape=(700, 10))

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
logi = LogisticRegression()

In [11]:
logi.fit(X_train,y_train)
y_pred = logi.predict(X_test)
print(y_pred)

[0 0 0 1 1 0 0 1 1 1 1 0 1 0 1 0 0 1 0 1 1 1 1 0 0 0 0 0 0 1 1 0 1 1 1 0 1
 1 0 0 0 0 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0
 1 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 1 0 1 1 1 1 0 0 0 0 0 1 0 0 0 1
 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 1 1 0 0 1 1 1 1 0 0 0 1 1
 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0
 0 1 1 0 1 1 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0
 0 1 0 0 0 0 0 1 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 0 1
 0 0 1 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 0 1
 0 1 0 0]


In [14]:
# logi.predict_proba(X_test)

In [15]:
# Performance metrics 
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [16]:
acc = accuracy_score(y_test,y_pred)
print(acc)

cm = confusion_matrix(y_test,y_pred)
print(cm)

creport = classification_report(y_test,y_pred)
print(creport)

0.9166666666666666
[[146  11]
 [ 14 129]]
              precision    recall  f1-score   support

           0       0.91      0.93      0.92       157
           1       0.92      0.90      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300



In [171]:
# Hyperparameter tuning and Cross validation

In [172]:
model = LogisticRegression()

penalty=['l1', 'l2', 'elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']

In [173]:
# params = dict(penalty=penalty,C= c_values,solver = solver) # getting error

In [180]:
params = [
    {'penalty': ['l1'], 'C': c_values, 'solver': ['liblinear', 'saga'], 'max_iter': [1000]},
    {'penalty': ['l2'], 'C': c_values, 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'], 'max_iter': [1000]},
    {'penalty': ['elasticnet'], 'C': c_values, 'solver': ['saga'], 'l1_ratio': [0.5], 'max_iter': [1000]},
]


In [175]:
from sklearn.model_selection import StratifiedKFold
cv = StratifiedKFold()

In [176]:
from sklearn.model_selection import GridSearchCV

In [177]:
grid = GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',n_jobs=-1,cv=cv)
grid

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [1000],
                          'penalty': ['l1'], 'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [1000],
                          'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'max_iter': [1000], 'penalty': ['elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [178]:
grid.fit(X_train,y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid=[{'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [1000],
                          'penalty': ['l1'], 'solver': ['liblinear', 'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'max_iter': [1000],
                          'penalty': ['l2'],
                          'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                     'saga']},
                         {'C': [100, 10, 1.0, 0.1, 0.01], 'l1_ratio': [0.5],
                          'max_iter': [1000], 'penalty': ['elasticnet'],
                          'solver': ['saga']}],
             scoring='accuracy')

In [181]:
grid.best_params_

{'C': 0.01,
 'l1_ratio': 0.5,
 'max_iter': 1000,
 'penalty': 'elasticnet',
 'solver': 'saga'}

In [183]:
grid.best_score_

np.float64(0.927142857142857)

In [185]:
y_pred = grid.predict(X_test)

In [189]:
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
classification_report=classification_report(y_test,y_pred)
print(classification_report)
confusion_mat = confusion_matrix(y_test,y_pred)
print(confusion_mat)

0.92
              precision    recall  f1-score   support

           0       0.90      0.95      0.93       157
           1       0.94      0.89      0.91       143

    accuracy                           0.92       300
   macro avg       0.92      0.92      0.92       300
weighted avg       0.92      0.92      0.92       300

[[149   8]
 [ 16 127]]
