In [49]:
import numpy as np

In [50]:
# array creation
# 1d
a = np.array([1, 2, 3])
print(a.shape)

(3,)


In [51]:
# 2d
a2 = a.reshape(1, 3)
print(a2)

# directly create 2d array
a3 = np.array([[1, 2, 3]])
print(a3)
a3.shape
a4 = np.array([[1], [2], [3]])
print(a4)

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]


In [52]:
a.reshape(3, 1)

array([[1],
       [2],
       [3]])

In [64]:
print(a.dtype)
b = [2343,43]
print(type(b))

int64
<class 'list'>


# Creating ranges array

In [53]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
np.arange(1,10,2).reshape(5,1)

array([[1],
       [3],
       [5],
       [7],
       [9]])

In [55]:
# Creating array with ones
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [56]:
# creating zeroes
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
# creating identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Attributes of numpy array

In [59]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape : ',b.shape)
print('ndim : ',b.ndim)
print('Size : ',b.size)
print("dtype: ",b.dtype)
print("Itemsize: ",b.itemsize)

Shape :  (2, 3)
ndim :  2
Size :  6
dtype:  int64
Itemsize:  8


In [61]:
# numpy vector operations
arr1 = np.array([1, 2, 3,4,5])
arr2 = np.array([10, 20, 30,40,50]) 
print("Addition :",arr1 + arr2)
print("Subtraction :",arr1 - arr2)
print("Multiplication :",arr1 * arr2)   
print("Division :",arr1 / arr2)
print("Power :",arr1 ** arr2)

Addition : [11 22 33 44 55]
Subtraction : [ -9 -18 -27 -36 -45]
Multiplication : [ 10  40  90 160 250]
Division : [0.1 0.1 0.1 0.1 0.1]
Power : [                   1              1048576      205891132094649
                    0 -6776596920136667815]


In [66]:
# universal functions
arr3 = np.array([1, 2, 3, 4, 5])
print("Sqrt: ",np.sqrt(arr3))
print("Exp: ",np.exp(arr3))
print("Sin: ",np.sin(arr3))
print("Cos: ",np.cos(arr3))
print("Log: ",np.log(arr3))


Sqrt:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exp:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Sin:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Cos:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Log:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [78]:
# array slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [82]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [90]:
# arr[0:2,2:]
arr[0:2,1:]

array([[2, 3, 4],
       [6, 7, 8]])

In [92]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [94]:
# modifying array
arr[0,0] = 100
print(arr)
arr[2:] =100
print(arr) 

[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]
[[100   2   3   4]
 [  5   6   7   8]
 [100 100 100 100]]


In [99]:
# Statistical concepts
# --Normalisation => to have a mean 0 and std 1
data  = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)
normalised_data = (data-mean)/std
print('Normalised data: ',normalised_data)  

Normalised data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [101]:
print('Mean: ',np.mean(data))
print('Median: ',np.median(data))
print('Variance: ',np.var(data))
print('Std: ',np.std(data))


Mean:  3.0
Median:  3.0
Variance:  2.0
Std:  1.4142135623730951


In [109]:
# logical operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data <= 8)] 

array([5, 6, 7, 8])